### ISSUE TITLE
Forward Specific Tool Front-End Environment Variables to Tool Back-Ends?

### ISSUE THREAD

**Issue by samuelkgutierrez** [scalability-llnl/LaunchMON#6]
Hi,

Is there a way to forward specified environment variables from a tool front-end to tool back-ends using LaunchMON?

Thanks,

Sam

**Comment by dongahn** [comment]
Hi Sam,

I have front-end API calls (i.e., LMON_fe_putToBeDaemonEnv() and MON_fe_putToMwDaemonEnv()) for this purpose, but unfortunately they have never been fully implemented. 

So, on an RM platform that supports the environment-variable forwarding by default (e.g., SLURM), LaunchMON will propagate the FEN env variables to the tool daemons launched. On a system that does not support this by default (e.g., Blue Gene/Q), the env variables will not be forwarded. 

I don't have an immediate plan (nor time) to implement this functionality. Solving this generally will probably require one to extend  LMONP with "lmonp_febe_env_forward" and "lmonp_femw_env_forward." I may revamp  LMONP with google's protobuf as part of my Flux effort and I can consider this as part of that work. But this won't happen in the near future. 

Depending on the underlying resource manager, you may be able to forward your FEN env variables by modifying the launchmon's bulk launch string, though. If you are using orterun, however you will have to see if its co-spawn capability (MPIR debug interface variant) supports environment variable propagation (I doubt it though). Sorry.

Best,
Dong

**Comment by samuelkgutierrez** [comment]
Hi Dong,

I have a workaround, so no worries on my end -- just checking.

Thanks for the detailed response!

Sam
